/**
 * Sunsam: textos de los menús nativos y de la bandeja para los idiomas que añade Sunsam.
 * Viven fuera de desktopMenu.ts para que las actualizaciones de upstream no choquen con ellos.
 */
import type { DesktopMenuLocaleMessages } from "./desktopMenu.js";
import type { BaseLocale, Locale } from "./protocol.js";

export const SUNSAM_DESKTOP_MENU_MESSAGES: Record<
  Exclude<Locale, BaseLocale>,
  DesktopMenuLocaleMessages
> = {
  "es-ES": {
    "titleBar.menu.file": "Archivo",
    "titleBar.menu.edit": "Editar",
    "titleBar.menu.view": "Ver",
    "titleBar.menu.window": "Ventana",
    "titleBar.menu.help": "Ayuda",
    "titleBar.menu.file.newTask": "Nueva tarea",
    "titleBar.menu.file.openWorkspace": "Abrir espacio de trabajo",
    "titleBar.menu.file.closeWindow": "Cerrar ventana",
    "titleBar.menu.edit.undo": "Deshacer",
    "titleBar.menu.edit.redo": "Rehacer",
    "titleBar.menu.edit.cut": "Cortar",
    "titleBar.menu.edit.copy": "Copiar",
    "titleBar.menu.edit.paste": "Pegar",
    "titleBar.menu.edit.delete": "Eliminar",
    "titleBar.menu.edit.selectAll": "Seleccionar todo",
    "titleBar.menu.view.toggleFullScreen": "Pantalla completa",
    "titleBar.menu.view.actualSize": "Tamaño real",
    "titleBar.menu.view.zoomIn": "Acercar",
    "titleBar.menu.view.zoomOut": "Alejar",
    "titleBar.menu.window.minimize": "Minimizar",
    "titleBar.menu.window.zoom": "Zoom",
    "titleBar.menu.window.bringAllToFront": "Traer todo al frente",
    "titleBar.menu.app.services": "Servicios",
    "titleBar.menu.app.hide": "Ocultar {appName}",
    "titleBar.menu.app.hideOthers": "Ocultar otros",
    "titleBar.menu.app.showAll": "Mostrar todo",
    "titleBar.menu.app.quit": "Salir de {appName}",
    "titleBar.menu.help.about": "Acerca de ZCode",
    "titleBar.menu.help.whatsNew": "Novedades",
    "titleBar.menu.help.checkForUpdates": "Buscar actualizaciones",
    "titleBar.menu.help.toggleDevTools": "Herramientas de desarrollo",
    "titleBar.menu.help.resourceManager": "Administrador de recursos",
    "titleBar.menu.help.toggleZCodeStdioTap": "Capturar tráfico stdio del agente",
    "titleBar.menu.help.zcodeEndpoint": "ZCode Endpoint",
    "titleBar.menu.help.zcodeEndpoint.production": "Producción (predeterminado)",
    "titleBar.menu.help.zcodeEndpoint.test": "Pruebas",
    "titleBar.menu.help.zcodeEndpoint.custom": "Personalizado...",
    "titleBar.menu.help.zcodeEndpoint.reset": "Restablecer predeterminado",
    "titleBar.menu.help.feedback": "Enviar comentarios",
    "titleBar.menu.help.exportLogs": "Exportar registros",
    "titleBar.menu.help.clearAllData": "Borrar todos los datos",
    "desktopMenu.help.checkingForUpdates": "Buscando actualizaciones...",
    "desktopMenu.help.updateAvailableVersion": "Actualización disponible {version}",
    "desktopMenu.help.downloadingUpdateVersion": "Descargando actualización {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "Descargando actualización... {progress}",
    "desktopMenu.help.restartToUpdate": "Reiniciar para actualizar ({version})",
    "dock.menu.showCurrentWindow": "Mostrar ventana actual",
    "tray.tooltip": "ZCode",
    "tray.menu.openZCode": "Abrir ZCode",
    "tray.menu.quit": "Salir",
  },
  "pt-BR": {
    "titleBar.menu.file": "Arquivo",
    "titleBar.menu.edit": "Editar",
    "titleBar.menu.view": "Visualizar",
    "titleBar.menu.window": "Janela",
    "titleBar.menu.help": "Ajuda",
    "titleBar.menu.file.newTask": "Nova tarefa",
    "titleBar.menu.file.openWorkspace": "Abrir espaço de trabalho",
    "titleBar.menu.file.closeWindow": "Fechar janela",
    "titleBar.menu.edit.undo": "Desfazer",
    "titleBar.menu.edit.redo": "Refazer",
    "titleBar.menu.edit.cut": "Recortar",
    "titleBar.menu.edit.copy": "Copiar",
    "titleBar.menu.edit.paste": "Colar",
    "titleBar.menu.edit.delete": "Excluir",
    "titleBar.menu.edit.selectAll": "Selecionar tudo",
    "titleBar.menu.view.toggleFullScreen": "Tela cheia",
    "titleBar.menu.view.actualSize": "Tamanho real",
    "titleBar.menu.view.zoomIn": "Ampliar",
    "titleBar.menu.view.zoomOut": "Reduzir",
    "titleBar.menu.window.minimize": "Minimizar",
    "titleBar.menu.window.zoom": "Zoom",
    "titleBar.menu.window.bringAllToFront": "Trazer tudo para a frente",
    "titleBar.menu.app.services": "Serviços",
    "titleBar.menu.app.hide": "Ocultar {appName}",
    "titleBar.menu.app.hideOthers": "Ocultar outros",
    "titleBar.menu.app.showAll": "Mostrar tudo",
    "titleBar.menu.app.quit": "Encerrar {appName}",
    "titleBar.menu.help.about": "Sobre o ZCode",
    "titleBar.menu.help.whatsNew": "Novidades",
    "titleBar.menu.help.checkForUpdates": "Verificar atualizações",
    "titleBar.menu.help.toggleDevTools": "Ferramentas de desenvolvedor",
    "titleBar.menu.help.resourceManager": "Gerenciador de recursos",
    "titleBar.menu.help.toggleZCodeStdioTap": "Capturar tráfego stdio do agente",
    "titleBar.menu.help.zcodeEndpoint": "ZCode Endpoint",
    "titleBar.menu.help.zcodeEndpoint.production": "Produção (padrão)",
    "titleBar.menu.help.zcodeEndpoint.test": "Testes",
    "titleBar.menu.help.zcodeEndpoint.custom": "Personalizado...",
    "titleBar.menu.help.zcodeEndpoint.reset": "Restaurar padrão",
    "titleBar.menu.help.feedback": "Enviar feedback",
    "titleBar.menu.help.exportLogs": "Exportar logs",
    "titleBar.menu.help.clearAllData": "Apagar todos os dados",
    "desktopMenu.help.checkingForUpdates": "Verificando atualizações...",
    "desktopMenu.help.updateAvailableVersion": "Atualização disponível {version}",
    "desktopMenu.help.downloadingUpdateVersion": "Baixando atualização {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "Baixando atualização... {progress}",
    "desktopMenu.help.restartToUpdate": "Reiniciar para atualizar ({version})",
    "dock.menu.showCurrentWindow": "Mostrar janela atual",
    "tray.tooltip": "ZCode",
    "tray.menu.openZCode": "Abrir ZCode",
    "tray.menu.quit": "Sair",
  },
  "fr-FR": {
    "titleBar.menu.file": "Fichier",
    "titleBar.menu.edit": "Édition",
    "titleBar.menu.view": "Présentation",
    "titleBar.menu.window": "Fenêtre",
    "titleBar.menu.help": "Aide",
    "titleBar.menu.file.newTask": "Nouvelle tâche",
    "titleBar.menu.file.openWorkspace": "Ouvrir un espace de travail",
    "titleBar.menu.file.closeWindow": "Fermer la fenêtre",
    "titleBar.menu.edit.undo": "Annuler",
    "titleBar.menu.edit.redo": "Rétablir",
    "titleBar.menu.edit.cut": "Couper",
    "titleBar.menu.edit.copy": "Copier",
    "titleBar.menu.edit.paste": "Coller",
    "titleBar.menu.edit.delete": "Supprimer",
    "titleBar.menu.edit.selectAll": "Tout sélectionner",
    "titleBar.menu.view.toggleFullScreen": "Plein écran",
    "titleBar.menu.view.actualSize": "Taille réelle",
    "titleBar.menu.view.zoomIn": "Zoom avant",
    "titleBar.menu.view.zoomOut": "Zoom arrière",
    "titleBar.menu.window.minimize": "Réduire",
    "titleBar.menu.window.zoom": "Zoom",
    "titleBar.menu.window.bringAllToFront": "Tout ramener au premier plan",
    "titleBar.menu.app.services": "Services",
    "titleBar.menu.app.hide": "Masquer {appName}",
    "titleBar.menu.app.hideOthers": "Masquer les autres",
    "titleBar.menu.app.showAll": "Tout afficher",
    "titleBar.menu.app.quit": "Quitter {appName}",
    "titleBar.menu.help.about": "À propos de ZCode",
    "titleBar.menu.help.whatsNew": "Nouveautés",
    "titleBar.menu.help.checkForUpdates": "Rechercher des mises à jour",
    "titleBar.menu.help.toggleDevTools": "Outils de développement",
    "titleBar.menu.help.resourceManager": "Gestionnaire de ressources",
    "titleBar.menu.help.toggleZCodeStdioTap": "Capturer le trafic stdio de l’agent",
    "titleBar.menu.help.zcodeEndpoint": "ZCode Endpoint",
    "titleBar.menu.help.zcodeEndpoint.production": "Production (par défaut)",
    "titleBar.menu.help.zcodeEndpoint.test": "Test",
    "titleBar.menu.help.zcodeEndpoint.custom": "Personnalisé...",
    "titleBar.menu.help.zcodeEndpoint.reset": "Rétablir la valeur par défaut",
    "titleBar.menu.help.feedback": "Envoyer un commentaire",
    "titleBar.menu.help.exportLogs": "Exporter les journaux",
    "titleBar.menu.help.clearAllData": "Effacer toutes les données",
    "desktopMenu.help.checkingForUpdates": "Recherche de mises à jour...",
    "desktopMenu.help.updateAvailableVersion": "Mise à jour disponible {version}",
    "desktopMenu.help.downloadingUpdateVersion": "Téléchargement de la mise à jour {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "Téléchargement de la mise à jour... {progress}",
    "desktopMenu.help.restartToUpdate": "Redémarrer pour mettre à jour ({version})",
    "dock.menu.showCurrentWindow": "Afficher la fenêtre actuelle",
    "tray.tooltip": "ZCode",
    "tray.menu.openZCode": "Ouvrir ZCode",
    "tray.menu.quit": "Quitter",
  },
  "ru-RU": {
    "titleBar.menu.file": "Файл",
    "titleBar.menu.edit": "Правка",
    "titleBar.menu.view": "Вид",
    "titleBar.menu.window": "Окно",
    "titleBar.menu.help": "Справка",
    "titleBar.menu.file.newTask": "Новая задача",
    "titleBar.menu.file.openWorkspace": "Открыть рабочее пространство",
    "titleBar.menu.file.closeWindow": "Закрыть окно",
    "titleBar.menu.edit.undo": "Отменить",
    "titleBar.menu.edit.redo": "Повторить",
    "titleBar.menu.edit.cut": "Вырезать",
    "titleBar.menu.edit.copy": "Копировать",
    "titleBar.menu.edit.paste": "Вставить",
    "titleBar.menu.edit.delete": "Удалить",
    "titleBar.menu.edit.selectAll": "Выбрать все",
    "titleBar.menu.view.toggleFullScreen": "Полноэкранный режим",
    "titleBar.menu.view.actualSize": "Реальный размер",
    "titleBar.menu.view.zoomIn": "Увеличить",
    "titleBar.menu.view.zoomOut": "Уменьшить",
    "titleBar.menu.window.minimize": "Свернуть",
    "titleBar.menu.window.zoom": "Изменить масштаб",
    "titleBar.menu.window.bringAllToFront": "Все окна — на передний план",
    "titleBar.menu.app.services": "Службы",
    "titleBar.menu.app.hide": "Скрыть {appName}",
    "titleBar.menu.app.hideOthers": "Скрыть остальные",
    "titleBar.menu.app.showAll": "Показать все",
    "titleBar.menu.app.quit": "Завершить {appName}",
    "titleBar.menu.help.about": "О программе ZCode",
    "titleBar.menu.help.whatsNew": "Что нового",
    "titleBar.menu.help.checkForUpdates": "Проверить обновления",
    "titleBar.menu.help.toggleDevTools": "Инструменты разработчика",
    "titleBar.menu.help.resourceManager": "Диспетчер ресурсов",
    "titleBar.menu.help.toggleZCodeStdioTap": "Перехват stdio-трафика агента",
    "titleBar.menu.help.zcodeEndpoint": "ZCode Endpoint",
    "titleBar.menu.help.zcodeEndpoint.production": "Рабочий (по умолчанию)",
    "titleBar.menu.help.zcodeEndpoint.test": "Тестовый",
    "titleBar.menu.help.zcodeEndpoint.custom": "Пользовательский...",
    "titleBar.menu.help.zcodeEndpoint.reset": "Сбросить по умолчанию",
    "titleBar.menu.help.feedback": "Отправить отзыв",
    "titleBar.menu.help.exportLogs": "Экспортировать журналы",
    "titleBar.menu.help.clearAllData": "Удалить все данные",
    "desktopMenu.help.checkingForUpdates": "Проверка обновлений...",
    "desktopMenu.help.updateAvailableVersion": "Доступно обновление {version}",
    "desktopMenu.help.downloadingUpdateVersion": "Загрузка обновления {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "Загрузка обновления... {progress}",
    "desktopMenu.help.restartToUpdate": "Перезапустить для обновления ({version})",
    "dock.menu.showCurrentWindow": "Показать текущее окно",
    "tray.tooltip": "ZCode",
    "tray.menu.openZCode": "Открыть ZCode",
    "tray.menu.quit": "Выйти",
  },
  "ko-KR": {
    "titleBar.menu.file": "파일",
    "titleBar.menu.edit": "편집",
    "titleBar.menu.view": "보기",
    "titleBar.menu.window": "윈도우",
    "titleBar.menu.help": "도움말",
    "titleBar.menu.file.newTask": "새 작업",
    "titleBar.menu.file.openWorkspace": "작업 공간 열기",
    "titleBar.menu.file.closeWindow": "윈도우 닫기",
    "titleBar.menu.edit.undo": "실행 취소",
    "titleBar.menu.edit.redo": "실행 복귀",
    "titleBar.menu.edit.cut": "오려두기",
    "titleBar.menu.edit.copy": "복사",
    "titleBar.menu.edit.paste": "붙여넣기",
    "titleBar.menu.edit.delete": "삭제",
    "titleBar.menu.edit.selectAll": "전체 선택",
    "titleBar.menu.view.toggleFullScreen": "전체 화면",
    "titleBar.menu.view.actualSize": "실제 크기",
    "titleBar.menu.view.zoomIn": "확대",
    "titleBar.menu.view.zoomOut": "축소",
    "titleBar.menu.window.minimize": "최소화",
    "titleBar.menu.window.zoom": "확대/축소",
    "titleBar.menu.window.bringAllToFront": "모두 앞으로 가져오기",
    "titleBar.menu.app.services": "서비스",
    "titleBar.menu.app.hide": "{appName} 가리기",
    "titleBar.menu.app.hideOthers": "기타 가리기",
    "titleBar.menu.app.showAll": "모두 보기",
    "titleBar.menu.app.quit": "{appName} 종료",
    "titleBar.menu.help.about": "ZCode 정보",
    "titleBar.menu.help.whatsNew": "새로운 기능",
    "titleBar.menu.help.checkForUpdates": "업데이트 확인",
    "titleBar.menu.help.toggleDevTools": "개발자 도구",
    "titleBar.menu.help.resourceManager": "리소스 관리자",
    "titleBar.menu.help.toggleZCodeStdioTap": "에이전트 stdio 트래픽 캡처",
    "titleBar.menu.help.zcodeEndpoint": "ZCode Endpoint",
    "titleBar.menu.help.zcodeEndpoint.production": "프로덕션(기본값)",
    "titleBar.menu.help.zcodeEndpoint.test": "테스트",
    "titleBar.menu.help.zcodeEndpoint.custom": "사용자 지정...",
    "titleBar.menu.help.zcodeEndpoint.reset": "기본값으로 재설정",
    "titleBar.menu.help.feedback": "피드백 보내기",
    "titleBar.menu.help.exportLogs": "로그 내보내기",
    "titleBar.menu.help.clearAllData": "모든 데이터 지우기",
    "desktopMenu.help.checkingForUpdates": "업데이트 확인 중...",
    "desktopMenu.help.updateAvailableVersion": "업데이트 사용 가능 {version}",
    "desktopMenu.help.downloadingUpdateVersion": "업데이트 다운로드 중 {version}...",
    "desktopMenu.help.downloadingUpdateProgress": "업데이트 다운로드 중... {progress}",
    "desktopMenu.help.restartToUpdate": "재시작하여 업데이트 ({version})",
    "dock.menu.showCurrentWindow": "현재 윈도우 보기",
    "tray.tooltip": "ZCode",
    "tray.menu.openZCode": "ZCode 열기",
    "tray.menu.quit": "종료",
  },
};
